# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7a35tcpg236-1
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir E:/vivado/Vivado/2014.4/examples/Vivado_Tutorial/Projects/struc_mux/struc_mux.cache/wt [current_project]
set_property parent.project_path E:/vivado/Vivado/2014.4/examples/Vivado_Tutorial/Projects/struc_mux/struc_mux.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:basys3:part0:1.1 [current_project]
read_verilog -library xil_defaultlib E:/vivado/Vivado/2014.4/examples/Vivado_Tutorial/Projects/struc_mux/mux_4x1.v
catch { write_hwdef -file mux_4x1.hwdef }
synth_design -top mux_4x1 -part xc7a35tcpg236-1
write_checkpoint -noxdef mux_4x1.dcp
catch { report_utilization -file mux_4x1_utilization_synth.rpt -pb mux_4x1_utilization_synth.pb }
