# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7a200tfbg676-2
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir E:/vivado/Vivado/2014.4/examples/Vivado_Tutorial/Projects/lab_6_adder/lab_6_adder.cache/wt [current_project]
set_property parent.project_path E:/vivado/Vivado/2014.4/examples/Vivado_Tutorial/Projects/lab_6_adder/lab_6_adder.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:ac701:part0:1.1 [current_project]
read_verilog -library xil_defaultlib E:/vivado/Vivado/2014.4/examples/Vivado_Tutorial/Projects/lab_6_adder/adder.v
catch { write_hwdef -file adder.hwdef }
synth_design -top adder -part xc7a200tfbg676-2
write_checkpoint -noxdef adder.dcp
catch { report_utilization -file adder_utilization_synth.rpt -pb adder_utilization_synth.pb }
