# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
debug::add_scope template.lib 1
set_msg_config -id {Common-41} -limit 4294967295
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000

create_project -in_memory -part xc7a35tcpg236-1
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir E:/vivado/Vivado/2014.4/examples/Vivado_Tutorial/Projects/lab12/lab12.cache/wt [current_project]
set_property parent.project_path E:/vivado/Vivado/2014.4/examples/Vivado_Tutorial/Projects/lab12/lab12.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:basys3:part0:1.1 [current_project]
read_verilog -library xil_defaultlib E:/vivado/Vivado/2014.4/examples/Vivado_Tutorial/Projects/lab12/FSM.v
read_xdc E:/vivado/Vivado/2014.4/examples/Vivado_Tutorial/Projects/lab12/lab12.srcs/constrs_1/imports/lab12/n.xdc
set_property used_in_implementation false [get_files E:/vivado/Vivado/2014.4/examples/Vivado_Tutorial/Projects/lab12/lab12.srcs/constrs_1/imports/lab12/n.xdc]

read_xdc E:/vivado/Vivado/2014.4/examples/Vivado_Tutorial/Projects/lab12/n.xdc
set_property used_in_implementation false [get_files E:/vivado/Vivado/2014.4/examples/Vivado_Tutorial/Projects/lab12/n.xdc]

catch { write_hwdef -file FSM.hwdef }
synth_design -top FSM -part xc7a35tcpg236-1
write_checkpoint -noxdef FSM.dcp
catch { report_utilization -file FSM_utilization_synth.rpt -pb FSM_utilization_synth.pb }
